"""refactor facilities

Revision ID: 7d08b9ffa497
Revises: 2af321b8a558
Create Date: 2025-03-05 09:50:23.484930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d08b9ffa497"
down_revision: Union[str, None] = "2af321b8a558"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms_facilities", sa.Column("room_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "rooms_facilities", sa.Column("facility_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "rooms_facilities_rooms_id_fkey", "rooms_facilities", type_="foreignkey"
    )
    op.drop_constraint(
        "rooms_facilities_facilities_id_fkey", "rooms_facilities", type_="foreignkey"
    )
    op.create_foreign_key(None, "rooms_facilities", "rooms", ["room_id"], ["id"])
    op.create_foreign_key(
        None, "rooms_facilities", "facilities", ["facility_id"], ["id"]
    )
    op.drop_column("rooms_facilities", "facilities_id")
    op.drop_column("rooms_facilities", "rooms_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms_facilities",
        sa.Column("rooms_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "rooms_facilities",
        sa.Column("facilities_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "rooms_facilities", type_="foreignkey")
    op.drop_constraint(None, "rooms_facilities", type_="foreignkey")
    op.create_foreign_key(
        "rooms_facilities_facilities_id_fkey",
        "rooms_facilities",
        "facilities",
        ["facilities_id"],
        ["id"],
    )
    op.create_foreign_key(
        "rooms_facilities_rooms_id_fkey",
        "rooms_facilities",
        "rooms",
        ["rooms_id"],
        ["id"],
    )
    op.drop_column("rooms_facilities", "facility_id")
    op.drop_column("rooms_facilities", "room_id")
    # ### end Alembic commands ###
