"""cost to price rooms

Revision ID: 6dfec37e8313
Revises: 2a5cb4e2c6cb
Create Date: 2025-02-27 17:35:02.884118

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "6dfec37e8313"
down_revision: Union[str, None] = "2a5cb4e2c6cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
