"""booking price update

Revision ID: efd09ef7eff2
Revises: 35b0d0661487
Create Date: 2025-02-28 10:53:56.050036

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "efd09ef7eff2"
down_revision: Union[str, None] = "35b0d0661487"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
